#!/usr/bin/env python3

with open("markup.html") as f:
	html = f.read()
with open("style.css") as f:
	css = f.read()
with open("script.js") as f:
	js = f.read()
with open("config.js") as f:
	config = f.read()

html = html.replace('<link rel="stylesheet" href="style.css">', f'<style>\n{css}</style>')
html = html.replace('<script src="script.js"></script>', f'<script>\n{js}</script>')
html = html.replace('<script src="config.js"></script>', f'<script>\n{config}</script>')

with open("Oendlorna.html", "w") as f:
	f.write(html)
