#!/bin/bash
#$1: Parent folder of wt. Must not have a trailing slash.
cd ..
rsync -avr web-tools/ "$1"/wt --exclude .git --exclude index.html --exclude readme.md --exclude towt --exclude Xidash --exclude nu.py --exclude swin.xml
cd "$1"/wt
patch Timer/Timer_English.html linkindex.patch
mv RandomMath rm
mv Swinmoi sm
mv Timer tm
mv rm/RandomMath.html rm/index.html
mv sm/Swinmoi.html sm/index.html
mv tm/Timer_Korean.html tm/index.html
rm linkindex.patch
